### PR TITLE
Using filters in "list" request.

### PR DESCRIPTION
**Pull request by levinside**
Must-have feature for "list" rows.

### CODE REVIEW

**Comment by tomaskazatel** [comment]
Hi, thanks a lot for another merge request, but this is not a very robust solution. I'll take a look at the filtering and try to design my own solution by the end of the week. However, I will be very happy for a follow-up review if you are interested.

**Comment by levinside** [comment]
Yep...
By the way, I'm not familiar with TypeScript right now.
¯\_(ツ)_/¯

**Comment by levinside** [comment]
Hi, is there are any news about filter implementation?

**Comment by tomaskazatel** [comment]
Sorry for my lack, but i have many thinks to do around my primary job. I will have some time in next week. Give me please time to implement this functionality. Have a nice day.

**Comment by IceHarley** [comment]
Hi, I am waiting for filters too )

**Comment by bcigdemoglu** [comment]
Hello, I am also waiting on filters. Would be huge huge win for us!

**Pull request closed without merging**
